[
server
]
   runOnSave = true
   
   [
browser
]
   serverAddress = "0.0.0.0"
   serverPort = 8501
   
   [
global
]
   developmentMode = false
   
   [
client
]
   showErrorDetails = false
   
   [
runner
]
   fastReruns = true
   
   [
theme
]
   primaryColor = "#F63366"
   backgroundColor = "#FFFFFF"
   secondaryBackgroundColor = "#F0F2F6"
   textColor = "#262730"
   font = "sans serif"